spring.application.name=APIEMT
api.externa.URL=https://openapi.emtmadrid.es
api.externa.accessToken=9d3e02c2-586e-11f1-9b5b-fe13246bc028
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration